name: BasicWorkflow                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-20.04                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step"

  integration:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
    continue-on-error: true

  artifact:
    needs: integration
    runs-on: ubuntu-20.04
    steps:
      - name: Create Artifact
        run: echo "hello" > hello.txt
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: hello.txt
          
  prod:
    needs: artifact
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a deploy step"
